spring:
  datasource:
    url: jdbc:mysql://192.168.1.235:3306/osp-course?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  config-location: classpath:/mybatis-plus/*.xml
  configuration:
    call-setters-on-nulls: false
