spring:
  datasource:
    hikari:
      connection-test-query: select 1
    sourceone:
      jdbc-url: jdbc:mysql://10.123.88.147:3306/osp-course?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    sourcetwo:
      jdbc-url: jdbc:mysql://10.123.88.149:3306/osp-course?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes: 192.168.36.3:6379,192.168.36.3:6380,192.168.36.3:6381,192.168.36.3:6382,192.168.36.3:6383,192.168.36.3:6384
  security:
    user:
      name: admin
      password: admin
mybatis-plus:
  mapper-locations: classpath:/mybatis-plus/*.xml
  configuration:
    call-setters-on-nulls: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
