spring:
  datasource:
    url: jdbc:mysql://10.123.88.147:3306/osp-course?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.7.115
    port: 6379
mybatis-plus:
  mapper-locations: classpath:/mybatis-plus/*.xml
  configuration:
    call-setters-on-nulls: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
