spring:
  datasource:
    sourceone:
      url: jdbc:mysql://10.123.88.147:3306/osp-course?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    sourcetwo:
      url: jdbc:mysql://10.123.88.117:3306/osp-course?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  security:
    user:
      name: admin
      password: admin
mybatis-plus:
  mapper-locations: classpath:/mybatis-plus/*.xml
  configuration:
    call-setters-on-nulls: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
