spring:
  datasource:
    url: jdbc:mysql://192.168.1.235:3306/osp-shop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  config-location: classpath:/mybatis-plus/*.xml
  configuration:
    call-setters-on-nulls: false
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1234/eureka